version: '3.8'
networks:
  laravel:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - phpmyadmin

    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: laravel.dockerfile
    container_name: laravel-php
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    ports:
      - "8000:8000"   # Map port 8000 of the container to port 8000 of the host
    depends_on:
      - mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    networks:
      - laravel

  mysql:
    image: mysql:latest
    container_name: laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_USER: ajaxbo
      MYSQL_PASSWORD: ajaxbo360
      MYSQL_ROOT_PASSWORD: ajaxbo360
      # MYSQL_SERVICE_TAG: dev
      MYSQL_SERVICE_NAME: mysql

    networks:
      - laravel
